- hosts: all
  become: true
  tasks:
    - name: Run multiple commands and save to a file
      shell: |
        command1
        command2
        command3
      args:
        executable: /bin/bash
      register: command_output

    - name: Save command output to a file
      copy:
        content: "{{ command_output.stdout_lines | join('\n') }}"
        dest: "/path/to/remote/output_{{ inventory_hostname }}.txt"

- hosts: localhost
  tasks:
    - name: Fetch the output files
      fetch:
        src: "/path/to/remote/output_{{ inventory_hostname }}.txt"
        dest: "/path/to/local/"
        flat: yes
